AWSTemplateFormatVersion: 2010-09-09
Description: The module will create a role with an inline policy to allow Coralogix to send events to an EventBridge event bus.
Parameters:
  ExternalIdSecret:
    Description: "ExternalIdSecret for sts:AssumeRole"
    Type: "String"
    AllowedPattern: "[\\w+=,.:\\/-]*"
  AWSAccount:
    Type: String
    Default: EU1
    Description: The AWS account that you want to deploy the integration in.
    AllowedValues:
      - dev
      - staging
      - EU1
      - EU2
      - AP1
      - Ap2
      - AP3
      - US1
      - US2
      - CustomEndpoint
  RoleName:
    Type: String
    Description: The name of the role that will be created.
  CustomAccountId:
    Type: String
    Description: In case you want to use a custom coralogix account, enter the aws account id that you want to use.
    Default: ""
    AllowedPattern: "[0-9]*"
  CoralogixCompanyId:
    Type: String
    Description: Your coralogix account company ID, will be used for security validation.
    AllowedPattern: "[0-9]*"

Mappings:
  CoralogixEnvironment:
    dev:
      ID: 233273809180
      RoleSuffix: dev01
    staging:
      ID: 233221153619
      RoleSuffix: stg1
    EU1:
      ID: 625240141681
      RoleSuffix: eu1
    EU2:
      ID: 625240141681
      RoleSuffix: eu2
    AP1:
      ID: 625240141681
      RoleSuffix: ap1
    Ap2:
      ID: 625240141681
      RoleSuffix: ap2
    AP3:
      ID: 025066248247
      RoleSuffix: ap3
    US1:
      ID: 625240141681
      RoleSuffix: us1
    US2:
      ID: 739076534691
      RoleSuffix: us2
    CustomEndpoint:
      ID: 000000000000
      RoleSuffix: custom
Conditions:
  IsCustomAccountId: !Not [!Equals [!Ref CustomAccountId, ""]]
Resources:
  CoralogixAwsMetricsRole:
    Type: AWS::IAM::Role
    Properties:
      Description: description
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - "arn:aws:iam::${aws_account_id}:role/coralogix-ingestion-${role_suffix}"
                - aws_account_id: !If
                    - IsCustomAccountId
                    - !Ref CustomAccountId
                    - !FindInMap [CoralogixEnvironment, !Ref AWSAccount, "ID"]
                  role_suffix: !FindInMap [CoralogixEnvironment, !Ref AWSAccount, "RoleSuffix"]
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub
                  - "${ExternalIdSecret}@${company_id}"
                  - ExternalIdSecret: !Ref ExternalIdSecret
                    company_id: !Ref CoralogixCompanyId
      Policies:
        - PolicyName: CoralogixMetricsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - tag:GetResources
                  - cloudwatch:GetMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - apigateway:GET
                  - autoscaling:DescribeAutoScalingGroups
                  - aps:ListWorkspaces
                  - dms:DescribeReplicationInstances
                  - dms:DescribeReplicationTasks
                  - ec2:DescribeTransitGatewayAttachments
                  - ec2:DescribeSpotFleetRequests
                  - storagegateway:ListGateways
                  - storagegateway:ListTagsForResource
                  - rds:Describe*
                  - rds:List*
                  - ecs:Describe*
                  - ecs:List*
                Resource: "*"

Outputs:
  CoralogixAwsMetricsRoleArn:
    Description: The ARN of the Coralogix AWS Metrics role.
    Value: !GetAtt CoralogixAwsMetricsRole.Arn
