name: Template Sync

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - aws-shipper-sync

env:
  REPO_BUCKET_PREFIX: coralogix-serverless-repo
  REPO_PACKAGE_ZIP: coralogix-aws-shipper.zip
  AWS_SHIPPER_REPO: coralogix/coralogix-aws-shipper
  CFN_INTEGRATION_DIR: aws-integrations/aws-shipper-lambda
  CLOUDFORMATION_REPO: coralogix/cloudformation-coralogix-aws


jobs:
  get-template:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout coralogix-aws-shipper repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.AWS_SHIPPER_REPO }}
          token: ${{ secrets.GH_TOKEN }}

      - name: get last commit_message
        id: commits
        run: |
          echo "last_commit=$(git log -1 --pretty=%B -- template.yaml | tr '\n' ' ' )" >> $GITHUB_OUTPUT

      - run: sudo snap install yq
        # Update the CodeUri property of all AWS::Serverless::Function resources using Yq
      - name: update-template
        run: |
          set -xv
          yq -i '(.Resources.[] | 
            select(
              has("Type") 
              and .Type == "AWS::Serverless::Function" 
              and .Properties.CodeUri != null) | 
            .Properties.CodeUri) |= "s3://${{ env.REPO_BUCKET_PREFIX }}-${AWS::Region}/${{ env.REPO_PACKAGE_ZIP }}"' ./template.yaml

          cat ./template.yaml | grep -i codeuri        
          set +xv

      - name: store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: store
          path: |
            ./template.yaml
            ./README.md
            ./CHANGELOG.md
    outputs:
      last_commit: ${{ steps.commits.outputs.last_commit }}


  sync-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: get-template
    # strategy:
    #   matrix:
    #     file:
    #     - name: template.yaml
    #       commit: ${{ needs.get-template.outputs.last_commit }}

    #     - name: README.md
    #       commit: ${{ needs.get-template.outputs.readme_commit }}

    #     - name: CHANGELOG.md 
    #       commit: ${{ needs.get-template.outputs.changelog_commit }}

    steps:
      - uses: actions/checkout@v3
        id: checkout
      - run: mkdir .tmp

      - name: download template
        uses: actions/download-artifact@v3
        with:
          name: store
          path: .tmp
        
      - run: sudo snap install yq
      - name: git-add
        id: changes
  
        # git add files if they've changed
        run: |
          set -xv
          ls -ltr .tmp
          mkdir -p ${{ env.CFN_INTEGRATION_DIR }}
          mv -v ./.tmp/* ${{ env.CFN_INTEGRATION_DIR }}/

          git add ${{ env.CFN_INTEGRATION_DIR }}/  
          git status
          set +xv

      # Commit all changed files back to the repository
      - uses: planetscale/ghcommit-action@v0.1.19
        with:
          commit_message: ${{ needs.get-template.outputs.last_commit }}
          repo: ${{ env.CLOUDFORMATION_REPO }}
          branch: cds-724
          file_pattern: '*.yaml *.md' 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}